### PR TITLE
Simplify Package Name, Add JSON config option

### PR DESCRIPTION
**Pull request by HungryGnu**
I appreciate this package! It saved me a lot of time.

I'm proposing two improvements:
1. Simplify the package name `pkce_client`, its a simpler, more memorable import.  It is still open on PyPI last I checked(8/20/24).  I think you should add this as a package in PyPI. Your solution is a top hit in google.
2. `PkceLoginConfig.from_config_file()` This adds the ability to load a JSON config (format in README.md) that saves time when you are using the same PKCE endpoint frequently.

I think you should deploy your package to PyPI!

### CODE REVIEW

**Comment by CamiloTerevinto** [comment]
Hi @HungryGnu, thanks for this PR. This package is on PyPI already, you can find it here: https://pypi.org/project/TerevintoSoftware.PkceClient/

I don't mind the changes in this PR that add support for the JSON config, but:

* I'm not open to updating the package's namespace, all my packages have the same prefix.
* There are a number of cache files that need to be excluded in the .gitignore and removed from the branch.
* The changes to pyproject.toml removed `[project.urls]`, which would remove the GitHub URLs from PyPI so it's not acceptable.

FYI, I stopped using this package myself when I found this one: https://github.com/AzureAD/microsoft-authentication-library-for-python

**Review by CamiloTerevinto — CHANGES_REQUESTED** [review]
Hi @HungryGnu, thanks for this PR. This package is on PyPI already, you can find it here: https://pypi.org/project/TerevintoSoftware.PkceClient/

I don't mind the changes in this PR that add support for the JSON config, but:

* I'm not open to updating the package's namespace, all my packages have the same prefix.
* There are a number of cache files that need to be excluded in the .gitignore and removed from the branch.
* The changes to pyproject.toml removed `[project.urls]`, which would remove the GitHub URLs from PyPI so it's not acceptable.

**Comment by CamiloTerevinto** [comment]
For what it's worth, I stopped using this package myself when I found this one: https://github.com/AzureAD/microsoft-authentication-library-for-python

**Comment by HungryGnu** [comment]
I updated the pull request. I restored the URL's and the 'terevintosoftware' namespace.

Poetry doesn't allow the dot in the namespace, not sure if that is a dealbreaker for that particular change.

I'll take a look at MSAL. Thanks for the tip!

**Pull request closed without merging**
